# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  scaTeamPath: '/Champions/Back2USSR'
  scaThreshold: 'false' #true or false
  scaHigh: '19' #Number or High before breaking build
  scaMedium: '10'
  scaLow: '15'
  dependencyFolderExclusion: 'cvs,.svn,.hg,.git,.bzr,bin,obj,backup,.idea,node_modules'
  continueOnError: 'false'
  scaEnablePolicyViolations: true

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  

- task: checkmarx.cxsast.cx-scan-task.Application security testing@2022
  displayName: 'Application security testing'
  inputs:
    projectName: fgsdfdfgsdg
    serviceConnection: https://api-sca.checkmarx.net
    syncMode: true
    enableProxy: false
    enableSastScan: false
    enableDependencyScan: true
    dependencyFolderExclusion: ${{parameters.dependencyFolderExclusion}}
    scaVulnerabilityThreshold: ${{parameters.scaThreshold}}
    scaHigh: ${{parameters.scaHigh}}
    scaMedium: ${{parameters.scaMedium}}
    scaLow: ${{parameters.scaLow}}
    scaTeam: ${{parameters.scaTeamPath}}
    continueOnError: ${{parameters.continueOnError}}